"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-08-02 23:31:50.268649

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


#  Alembic identifikatorlari
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Bazani oldinga surish."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('emoji', sa.String(length=8), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    comment='Test kategoriyalari'
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_categories_order_index'), ['order_index'], unique=False)

    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=24), nullable=True),
    sa.Column('language', sa.String(length=8), server_default='uz', nullable=False),
    sa.Column('is_registered', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('role', sa.String(length=16), server_default='student', nullable=False),
    sa.Column('is_banned', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('ban_reason', sa.Text(), nullable=True),
    sa.Column('banned_at', sa.DateTime(), nullable=True),
    sa.Column('xp', sa.Integer(), server_default='0', nullable=False),
    sa.Column('streak_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('streak_updated_on', sa.DateTime(), nullable=True),
    sa.Column('notifications_enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('show_in_leaderboard', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    comment='Foydalanuvchilar'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_banned'), ['is_banned'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_registered'), ['is_registered'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_last_active_at'), ['last_active_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index('ix_users_role_banned', ['role', 'is_banned'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_telegram_id'), ['telegram_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)
        batch_op.create_index('ix_users_xp_desc', ['xp'], unique=False)

    op.create_table('tests',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('author_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('visibility', sa.String(length=16), server_default='link', nullable=False),
    sa.Column('answer_key', sa.String(length=256), nullable=True),
    sa.Column('questions_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('time_limit_sec', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='1', nullable=False),
    sa.Column('pass_score', sa.Integer(), server_default='60', nullable=False),
    sa.Column('show_answers', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('certificate_enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('views', sa.Integer(), server_default='0', nullable=False),
    sa.Column('attempts_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('avg_score', sa.Float(), server_default='0', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_tests_author_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_tests_category_id_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tests')),
    comment='Testlar'
    )
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tests_author_id'), ['author_id'], unique=False)
        batch_op.create_index('ix_tests_author_status', ['author_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tests_category_id'), ['category_id'], unique=False)
        batch_op.create_index('ix_tests_category_status', ['category_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tests_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_tests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tests_ends_at'), ['ends_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tests_number'), ['number'], unique=True)
        batch_op.create_index(batch_op.f('ix_tests_starts_at'), ['starts_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tests_status'), ['status'], unique=False)
        batch_op.create_index('ix_tests_status_visibility', ['status', 'visibility'], unique=False)
        batch_op.create_index(batch_op.f('ix_tests_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_tests_visibility'), ['visibility'], unique=False)

    op.create_table('attempts',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='in_progress', nullable=False),
    sa.Column('submitted_key', sa.String(length=256), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_sec', sa.Integer(), server_default='0', nullable=False),
    sa.Column('score', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_score', sa.Integer(), server_default='0', nullable=False),
    sa.Column('percentage', sa.Float(), server_default='0', nullable=False),
    sa.Column('grade', sa.String(length=4), nullable=True),
    sa.Column('is_passed', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('correct_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('wrong_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('skipped_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], name=op.f('fk_attempts_test_id_tests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_attempts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attempts')),
    comment='Yechish urinishlari'
    )
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempts_deadline'), ['deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_percentage'), ['percentage'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_status'), ['status'], unique=False)
        batch_op.create_index('ix_attempts_status_deadline', ['status', 'deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_test_id'), ['test_id'], unique=False)
        batch_op.create_index('ix_attempts_test_percentage', ['test_id', 'percentage'], unique=False)
        batch_op.create_index('ix_attempts_test_user', ['test_id', 'user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_attempts_user_status', ['user_id', 'status'], unique=False)

    op.create_table('test_media',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(length=256), nullable=False),
    sa.Column('file_unique_id', sa.String(length=128), nullable=True),
    sa.Column('media_type', sa.String(length=16), server_default='photo', nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('caption', sa.String(length=256), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], name=op.f('fk_test_media_test_id_tests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_media')),
    sa.UniqueConstraint('test_id', 'order_index', name='uq_test_media_test_order'),
    comment='Test varaqasi rasmlari'
    )
    with op.batch_alter_table('test_media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_media_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_media_test_id'), ['test_id'], unique=False)
        batch_op.create_index('ix_test_media_test_order', ['test_id', 'order_index'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """O'zgarishlarni orqaga qaytarish."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_media', schema=None) as batch_op:
        batch_op.drop_index('ix_test_media_test_order')
        batch_op.drop_index(batch_op.f('ix_test_media_test_id'))
        batch_op.drop_index(batch_op.f('ix_test_media_created_at'))

    op.drop_table('test_media')
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_attempts_user_status')
        batch_op.drop_index(batch_op.f('ix_attempts_user_id'))
        batch_op.drop_index('ix_attempts_test_user')
        batch_op.drop_index('ix_attempts_test_percentage')
        batch_op.drop_index(batch_op.f('ix_attempts_test_id'))
        batch_op.drop_index('ix_attempts_status_deadline')
        batch_op.drop_index(batch_op.f('ix_attempts_status'))
        batch_op.drop_index(batch_op.f('ix_attempts_started_at'))
        batch_op.drop_index(batch_op.f('ix_attempts_percentage'))
        batch_op.drop_index(batch_op.f('ix_attempts_deadline'))

    op.drop_table('attempts')
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tests_visibility'))
        batch_op.drop_index(batch_op.f('ix_tests_title'))
        batch_op.drop_index('ix_tests_status_visibility')
        batch_op.drop_index(batch_op.f('ix_tests_status'))
        batch_op.drop_index(batch_op.f('ix_tests_starts_at'))
        batch_op.drop_index(batch_op.f('ix_tests_number'))
        batch_op.drop_index(batch_op.f('ix_tests_ends_at'))
        batch_op.drop_index(batch_op.f('ix_tests_created_at'))
        batch_op.drop_index(batch_op.f('ix_tests_code'))
        batch_op.drop_index('ix_tests_category_status')
        batch_op.drop_index(batch_op.f('ix_tests_category_id'))
        batch_op.drop_index('ix_tests_author_status')
        batch_op.drop_index(batch_op.f('ix_tests_author_id'))

    op.drop_table('tests')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_xp_desc')
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_telegram_id'))
        batch_op.drop_index('ix_users_role_banned')
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_index(batch_op.f('ix_users_last_active_at'))
        batch_op.drop_index(batch_op.f('ix_users_is_registered'))
        batch_op.drop_index(batch_op.f('ix_users_is_banned'))
        batch_op.drop_index(batch_op.f('ix_users_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_order_index'))
        batch_op.drop_index(batch_op.f('ix_categories_name'))
        batch_op.drop_index(batch_op.f('ix_categories_created_at'))

    op.drop_table('categories')
    # ### end Alembic commands ###
