"""certificates

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-03 00:39:57.439272

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


#  Alembic identifikatorlari
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Bazani oldinga surish."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificates',
    sa.Column('serial', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('holder_name', sa.String(length=160), nullable=False),
    sa.Column('test_title', sa.String(length=160), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(length=4), nullable=False),
    sa.Column('rank', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_participants', sa.Integer(), server_default='0', nullable=False),
    sa.Column('file_id', sa.String(length=256), nullable=True),
    sa.Column('document_file_id', sa.String(length=256), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], name=op.f('fk_certificates_attempt_id_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], name=op.f('fk_certificates_test_id_tests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_certificates_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certificates')),
    comment='Berilgan sertifikatlar'
    )
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificates_attempt_id'), ['attempt_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_certificates_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificates_serial'), ['serial'], unique=True)
        batch_op.create_index(batch_op.f('ix_certificates_test_id'), ['test_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificates_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_certificates_user_test', ['user_id', 'test_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """O'zgarishlarni orqaga qaytarish."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_index('ix_certificates_user_test')
        batch_op.drop_index(batch_op.f('ix_certificates_user_id'))
        batch_op.drop_index(batch_op.f('ix_certificates_test_id'))
        batch_op.drop_index(batch_op.f('ix_certificates_serial'))
        batch_op.drop_index(batch_op.f('ix_certificates_created_at'))
        batch_op.drop_index(batch_op.f('ix_certificates_attempt_id'))

    op.drop_table('certificates')
    # ### end Alembic commands ###
